# Generated by Django 4.0.2 on 2022-02-22 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, choices=[('HOT', 'hot'), ('COLD', 'cold'), ('MED', 'medium'), ('SOLD', 'sold')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
