# Generated by Django 4.0.2 on 2022-03-03 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_lead_state_alter_lead_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, choices=[('HOT', 'hot'), ('COLD', 'cold'), ('MED', 'medium'), ('GREY', 'grey'), ('SUCC', 'success')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='user_id',
            field=models.ForeignKey(blank=True, help_text='Only Sales Representative', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='manager_id',
            field=models.ForeignKey(blank=True, help_text='Only Sales Admin', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Phone no'),
        ),
    ]
