# Generated by Django 4.0.2 on 2022-03-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_lead_created_at_alter_remark_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='remark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
